# FunImpute Configuration File
# This file contains all configurable parameters for the imputation analysis service

# Outlier Detection Parameters
iqr_multiplier: 1.5                    # Multiplier for IQR-based outlier detection (1.5 = standard, 2.0 = conservative)
outlier_percentage_threshold: 0.05     # Threshold for considering outlier percentage significant (5%)

# Missingness Mechanism Analysis Parameters
correlation_threshold: 0.3             # Minimum correlation for considering relationships significant
chi_square_alpha: 0.05                 # Significance level for chi-square independence tests
point_biserial_threshold: 0.2          # Minimum point-biserial correlation for MAR detection

# Data Quality Assessment Thresholds
skewness_threshold: 2.0                # Threshold for considering data highly skewed
missing_percentage_threshold: 0.8      # Threshold for recommending "Missing" constant (80%)

# Output File Paths
output_path: "output/imputation_suggestions.csv"    # Path for main suggestions output
audit_log_path: "output/audit_logs.jsonl"          # Path for detailed audit logs

# Monitoring and Observability
metrics_port: 8001                     # Port for Prometheus metrics server

# Advanced Settings (Optional)
# Uncomment and modify as needed for specific use cases

# max_related_columns: 2               # Maximum number of related columns to analyze for MAR
# confidence_boost_threshold: 0.8      # Threshold for applying confidence boosts
# business_rule_weight: 0.15           # Weight given to business rule presence in confidence calculation
